name: Frontend Deploy
on:
  push:
    branches: [main]
    paths:
      - 'Forward-client/**'

permissions:
  contents: read

jobs:
  deploy:
    environment: Frontend Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Forward-client
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: Forward-client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}

      # Keep js/css bundles cached
      - name: Deploy Assets to S3
        env:
          SOURCE_DIR: build/client
          DEST_BUCKET: s3://${{ secrets.S3_BUCKET }}
          
        run: |
          aws s3 sync $SOURCE_DIR $DEST_BUCKET \
            --exclude "index.html" \
            --delete \
            --cache-control "public, max-age=31536000, immutable"

      - name: Deploy HTML to S3
        env:
          SOURCE_DIR: build/client
          DEST_BUCKET: s3://${{ secrets.S3_BUCKET }}
        run: |
          aws s3 cp $SOURCE_DIR/index.html $DEST_BUCKET/index.html \
            --cache-control "no-cache, no-store, must-revalidate"

      - name: Invalidate CloudFront
        env:
          DIST_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DIST_ID \
            --paths "/*"
